apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-f2p6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0030-tenant/cin4s-839-0030-app/devfile-sample-f2p6@sha256:4a2f2c71e25f017ce505e8545568365e5ee36ef945db7d0ff81f53e2f9148172
        name: my-nodejs
        resources: {}
status: {}
